# Note: change the port mappings if port already used

version: "3.3"
services:
  cli:
    build: cli
    image: warr/php-cli
    command: crond -f -l 8
    volumes:
      - ../projects:/workspaces/laravel
      - ./ssh:/home/user/.ssh
      #- ./cli/cron:/etc/periodic/1min
      # - ./cli/test.txt:/test.txt
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 1.1.1.1  # dns server 1

  fpm:
    build: fpm
    volumes:
      - ../projects:/workspaces/laravel
    user: 1000:1000
    dns:
      - 1.1.1.1  # dns server 1

  nginx:
    # build: nginx
    image: nginx:1.21-alpine
    volumes:
      - ../projects:/workspaces/laravel
      - ./logs:/var/log/docker/nginx
      - ./sites:/etc/nginx/sites-enabled
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
      # - 8010:8000
      # - 8011:8001
      # - 8012:8002
      # - 8013:8003
    depends_on:
      - fpm

  # postgres:
  #   image: postgres:13-alpine
  #   environment:
  #     POSTGRES_DB: laravel
  #     POSTGRES_USER: root
  #     POSTGRES_HOST_AUTH_METHOD: trust
  
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example456
      MYSQL_DATABASE: laravel-app

# uncomment if need db management
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080


  # redis:
  #   image: redis:6.2-alpine

  # queue:
  #   build: supervisor
  #   image: supervisor
  #   volumes:
      # - ..:/workspaces/laravel
    # Switch to "webuser" before running `php artisan`
    # Declare command in list manner for environment variable expansion
    # command: ["cd /workspaces/laravel/partnered && php artisan queue:work --tries=3"]

